### ISSUE TITLE
Unable to deploy container due to java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by LucanMartin** [factionsecurity/faction#66]
I successfully build the image from github but during deployment image to container it;s failing on errors bellow:

`[ERROR] 2024-08-06 13:06:45.585 [main] DefaultClassFinder - Unable to read class [com.fuse.actions.appstore.InstallExtensionController]
java.lang.IllegalArgumentException: null
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.1.jar:5.1]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.1.jar:5.1]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.1.jar:5.1]
        at org.apache.struts2.convention.DefaultClassFinder.readClassDef(DefaultClassFinder.java:458) ~[struts2-convention-plugin-2.5.12.jar:2.5.12]
        at org.apache.struts2.convention.DefaultClassFinder.access$200(DefaultClassFinder.java:49) ~[struts2-convention-plugin-2.5.12.jar:2.5.12]
        at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.extractSuperInterfaces(DefaultClassFinder.java:511) ~[struts2-convention-plugin-2.5.12.jar:2.5.12]
        at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.visit(DefaultClassFinder.java:498) ~[struts2-convention-plugin-2.5.12.jar:2.5.12]`

**Comment by LucanMartin** [comment]
Is there any possibility to download from somewhere whole docker image in TAR format?

**Comment by summitt** [comment]
That error is known but has not stopped the application from running correctly. You can safely ignore it for now but we are working on fixing it when we get though some of out other backlog of issues.

**Comment by LucanMartin** [comment]
Yes, there are multiple errors on container. I added file with the logs.
Apache TOmcat is successfully running but without application Faction application running on it.
[docker-log-faction.txt](https://github.com/user-attachments/files/16560250/docker-log-faction.txt)

**Comment by summitt** [comment]
Took me a bit to get to this as I was presenting Faction at DEF CON last week. Thanks for sending the logs. From the logs it appears you have not started the mongo database. Did you run the `docker-compose up` command and if so can you confirm mongodb has started.

**Comment by summitt** [comment]
Just following up on this @LucanMartin . From the last logs it looks like the MONGO environemnt variables were not set in the container. 
` Missing value for property 'hibernate.ogm.datastore.database'`. 

Were you able to get this running.
